// <auto-generated />
using System;
using BackendWeb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendWeb.Migrations
{
    [DbContext(typeof(DatasContext))]
    partial class DatasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendWeb.Model.Student", b =>
                {
                    b.Property<int>("Id_student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_birth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Father_telephone")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("FullName_father")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("FullName_mother")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Mother_telephone")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Place_residence")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Surname")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id_student");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("BackendWeb.Model.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Login")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("accessLevel")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("rememberMe")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
